name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Reuse the build job from build.yml
  build:
    # Ignore draft PRs
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      PFX_BASE64_ENCODED: ${{ secrets.PFX_BASE64_ENCODED }}
      PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}

